//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestoranContext : DbContext
    {
        public RestoranContext()
            : base("name=RestoranContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dobavljac> Dobavljacs { get; set; }
        public virtual DbSet<Gost> Gosts { get; set; }
        public virtual DbSet<Jelo> Jeloes { get; set; }
        public virtual DbSet<Namirnica> Namirnicas { get; set; }
        public virtual DbSet<Pice> Pices { get; set; }
        public virtual DbSet<Porudzbenica> Porudzbenicas { get; set; }
        public virtual DbSet<Proizvod> Proizvods { get; set; }
        public virtual DbSet<Racun> Racuns { get; set; }
        public virtual DbSet<Rezervacija> Rezervacijas { get; set; }
        public virtual DbSet<Sektor> Sektors { get; set; }
        public virtual DbSet<StavkaPorudzbenice> StavkaPorudzbenices { get; set; }
        public virtual DbSet<StavkaRacuna> StavkaRacunas { get; set; }
        public virtual DbSet<Sto> Stoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
