//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public int BrojStola { get; set; }
        public int GostId { get; set; }
        public System.DateTime DatumVreme { get; set; }
        public int BrojRezervacije { get; set; }
    
        public virtual Gost Gost { get; set; }
        public virtual Sto Sto { get; set; }
    }
}
