//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaPorudzbenice
    {
        public int Id { get; set; }
        public int ProizvodId { get; set; }
        public int PorudzbenicaId { get; set; }
        public int Kolicina { get; set; }
    
        public virtual Porudzbenica Porudzbenica { get; set; }
        public virtual Proizvod Proizvod { get; set; }
    }
}
